version: '3.7'
services:
  database:
    container_name: database
    image: postgres:13.0-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database